TRAINING_DATA = [
    # --- Greeting (Greeting) ---
    ('hi', 'Greeting'),
    ('hello', 'Greeting'),
    ('hey', 'Greeting'),
    ('hey there', 'Greeting'),
    ('good morning', 'Greeting'),
    ('good evening', 'Greeting'),
    ('good afternoon', 'Greeting'),
    ('howdy', 'Greeting'),
    ('hi chatbot', 'Greeting'),
    ('hello i am here', 'Greeting'),
    ('greetings', 'Greeting'),
    ('hi bot', 'Greeting'),
    ('yo', 'Greeting'),
    ('hiya', 'Greeting'),
    ('morning', 'Greeting'),
    ('evening', 'Greeting'),
    ('hey brewbot', 'Greeting'),
    ('hello buddy', 'Greeting'),
    ('is anyone here', 'Greeting'),
    ('start', 'Greeting'),

    # --- Order (Order) ---
    # ('i want a coffee', 'Order'),  <-- Moved to Suggest
    ('can i order please', 'Order'),
    ('can i order please', 'Order'),
    ('i would like to buy a drink', 'Order'),
    ('place an order for me', 'Order'),
    ('get me a cappuccino', 'Order'),
    ('i will take an espresso', 'Order'),
    ('buy coffee', 'Order'),
    ('order now', 'Order'),
    ('i want to order it', 'Order'),
    ('yes order it', 'Order'),
    ('confirmed order', 'Order'),
    ('please place my order', 'Order'),
    ('one latte please', 'Order'),
    ('make me an americano', 'Order'),
    ('i\'ll have the specialty', 'Order'),
    ('checkout', 'Order'),
    ('can you buy it for me', 'Order'),
    ('yes please order', 'Order'),
    ('get it', 'Order'),
    ('purchase', 'Order'),
    ('yes', 'Order'),
    ('no', 'Order'),
    ('yeah', 'Order'),
    ('yep', 'Order'),
    ('nope', 'Order'),
    ('nah', 'Order'),

    # --- Suggest (Suggest) ---
    ('what do you recommend', 'Suggest'),
    ('surprise me', 'Suggest'),
    ('what should i drink', 'Suggest'),
    ('suggest something for me', 'Suggest'),
    ('i dont know what to order', 'Suggest'),
    ('help me choose a coffee', 'Suggest'),
    ('any recommendations', 'Suggest'),
    ('what is good today', 'Suggest'),
    ('help me pick', 'Suggest'),
    ('pick for me', 'Suggest'),
    ('what brew fits my mood', 'Suggest'),
    ('best coffee for right now', 'Suggest'),
    ('i want a recommendation', 'Suggest'),
    ('not sure what i want', 'Suggest'),
    ('give me a choice', 'Suggest'),
    ('suggest a cold drink', 'Suggest'),
    ('suggest a hot drink', 'Suggest'),
    ('help me decide', 'Suggest'),
    ('what fits the weather', 'Suggest'),
    ('give me your best pick', 'Suggest'),
    ('i want a coffee', 'Suggest'),
    ('get me a coffee', 'Suggest'),
    ('i need caffeine', 'Suggest'),
    ('brew me something', 'Suggest'),

    # --- Question (Question) ---
    ('what is a latte', 'Question'),
    ('how much caffeine is in espresso', 'Question'),
    ('what ingredients are in this', 'Question'),
    ('is this coffee sweet', 'Question'),
    ('how many calories', 'Question'),
    ('tell me about americano', 'Question'),
    ('how much is it', 'Question'),
    ('what is the price', 'Question'),
    ('caffeine content', 'Question'),
    ('is it healthy', 'Question'),
    ('what is in a macchiato', 'Question'),
    ('describe the cold brew', 'Question'),
    ('why is it called espresso', 'Question'),
    ('how do you make this', 'Question'),
    ('ingredients list', 'Question'),
    ('price of latte', 'Question'),
    ('is caffeine high', 'Question'),
    ('sugar level', 'Question'),
    ('sweetness', 'Question'),
    ('what is the best seller', 'Question'),

    # --- Complaint (Complaint) ---
    ('this is too bitter', 'Complaint'),
    ('this coffee is too bitter', 'Complaint'),
    ('i dont like this recommendation', 'Complaint'),
    ('that was not good', 'Complaint'),
    ('this coffee is too strong', 'Complaint'),
    ('not what i wanted', 'Complaint'),
    ('bad recommendation', 'Complaint'),
    ('terrible choice', 'Complaint'),
    ('i hate this', 'Complaint'),
    ('tastes like burnt beans', 'Complaint'),
    ('too cold', 'Complaint'),
    ('too hot', 'Complaint'),
    ('dislike', 'Complaint'),
    ('poor choice', 'Complaint'),
    ('don\'t suggest this again', 'Complaint'),
    ('this is awful', 'Complaint'),
    ('not happy', 'Complaint'),
    ('dissatisfied', 'Complaint'),
    ('something is wrong', 'Complaint'),
    ('waste of time', 'Complaint'),

    # --- Feedback (Feedback) ---
    ('that was great', 'Feedback'),
    ('loved it thank you', 'Feedback'),
    ('perfect recommendation', 'Feedback'),
    ('i enjoyed that coffee', 'Feedback'),
    ('five stars', 'Feedback'),
    ('that was exactly what i needed', 'Feedback'),
    ('good bot', 'Feedback'),
    ('well done', 'Feedback'),
    ('amazing pick', 'Feedback'),
    ('thank you so much', 'Feedback'),
    ('best bot ever', 'Feedback'),
    ('i like this', 'Feedback'),
    ('it was delicious', 'Feedback'),
    ('thanks for the help', 'Feedback'),
    ('helpful', 'Feedback'),
    ('spot on', 'Feedback'),
    ('excellent suggestion', 'Feedback'),
    ('really good', 'Feedback'),
    ('tasted great', 'Feedback'),
    ('happy with this', 'Feedback'),
    ('rate this recommendation', 'Feedback'),

    # --- Browse (Browse) ---
    ('show me the menu', 'Browse'),
    ('show me what you have', 'Browse'),
    ('what drinks do you have', 'Browse'),
    ('what options are available', 'Browse'),
    ('list all coffees', 'Browse'),
    ('what can i order', 'Browse'),
    ('menu items', 'Browse'),
    ('browse products', 'Browse'),
    ('view full list', 'Browse'),
    ('what is on the menu', 'Browse'),
    ('available menu', 'Browse'),
    ('let me see the coffees', 'Browse'),
    ('what can i buy', 'Browse'),
    ('choices', 'Browse'),
    ('options', 'Browse'),
    ('what items', 'Browse'),
    ('show products', 'Browse'),
    ('list menu', 'Browse'),
    ('see menu', 'Browse'),
    ('drinks', 'Browse'),

    # --- Goodbye (Goodbye) ---
    ('bye', 'Goodbye'),
    ('goodbye', 'Goodbye'),
    ('thanks see you later', 'Goodbye'),
    ('that will be all', 'Goodbye'),
    ('i am done', 'Goodbye'),
    ('exit', 'Goodbye'),
    ('stop chat', 'Goodbye'),
    ('see you later', 'Goodbye'),
    ('cya', 'Goodbye'),
    ('take care', 'Goodbye'),
    ('end conversation', 'Goodbye'),
    ('quit', 'Goodbye'),
    ('finish', 'Goodbye'),
    ('done for today', 'Goodbye'),
    ('signing off', 'Goodbye'),
    ('close', 'Goodbye'),
    ('no thanks', 'Goodbye'),
    ('nothing else', 'Goodbye'),
    ('that is it', 'Goodbye'),
    ('no more', 'Goodbye'),
]
